name: hubs
on:
  push:
  pull_request:
    branches: [master, dev, staging, prod]
  workflow_dispatch:

env:
  registryName: mozillareality
  containerName: hubs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-hubs
        uses: actions/checkout@v2
        with:
          repository: mozilla/hubs
          ref: feature/turkey
          path: "./hubs"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.registryName }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: hubs/
          file: hubs/RetPageOriginDockerfile
          tags: ${{ env.registryName }}/${{ env.containerName }}:${{ github.run_number  }}
          cache-from: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache
          cache-to: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache,mode=max
          push: true
      - name: pull request tag
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          fromTag=${{ env.registryName }}/${{ env.containerName }}:${{ github.run_number }}
          toTag=${{ env.registryName }}/${{ env.containerName }}:$PR_NUMBER
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $fromTag
          docker tag $fromTag $toTag
          sudo docker push $toTag
          echo "promoted :$fromTag to :$toTag"

  promote:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull <GITHUB_SHA>, re-tag, push
        run: |
          fromTag=${{ env.registryName }}/${{ env.containerName }}:${{ github.run_number }}
          toTag=${{ env.registryName }}/${{ env.containerName }}:${GITHUB_REF/'refs/heads/'/}        
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $fromTag
          docker tag $fromTag $toTag
          sudo docker push $toTag
          echo "promoted :$fromTag to :$toTag"
