name: hubs
on:
  push:
    branches: [master, dev, feature/turkey]
  workflow_dispatch:

env:
  registryName: mozillareality
  containerName: hubs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-hubs
        uses: actions/checkout@v2
        with:
          repository: mozilla/hubs
          ref: feature/turkey
          path: "./hubs"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.registryName }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: hubs/
          file: hubs/RetPageOriginDockerfile
          tags: ${{ env.registryName }}/${{ env.containerName }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache
          cache-to: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache,mode=max
          push: true

  promote:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull <GITHUB_SHA>, re-tag, push
        run: |
          shaTag=${{ env.registryName }}/${{ env.containerName }}:${{ github.sha }}
          envTag=${GITHUB_REF/'refs/heads/'/}        
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $shaTag
          docker tag $shaTag $envTag
          sudo docker push $envTag
          echo "promoted :$shaTag to :$envTag"
